# Site settings
title: 'Jason Dominiczak'
text_description: 'Data Nerd <span>&&</span> First Responder Advocate <span>&&</span> Speaker'
description: ''
url: ''
baseurl: ''
subtitle: 'I nerd out on everything.'
longtext: 'You can find me working on my fantasy football algorithm, analysing MCI responses, or brewing beer.  I started <a href="http://www.bargerstreetgroup.com">The Barger Street Group</a> which sits at the intersection of data science and critical incident response.'
googleAnalytics: 'UA-51066876-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jason Dominiczak'
  email: jason@bargerstreetgroup.com
  twitter_username: jasondominiczak
  github_username:  jdominiczak
  linkedin_username:  jasondominiczak
  flickr_username: jdominiczak
  instagram_username: jasondominiczak

#defaults:
#  -
#    scope:
#      path: ''
#      type: 'posts'
#    values:
#        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
