# Site settings
title: 'Jason Dominiczak'
text_description: 'Programmer <span>&&</span> Homebrewer <span>&&</span> Data Nerd'
description: 'Programmer, Homebrewer, Data Nerd, and Author of BrewingNerd.com'
url: ''
baseurl: ''
subtitle: 'I nerd out on everything.'
longtext: 'You can find me working on my fantasy football scoring algorithm, predicting the NCAA bracket, or finding fraud in Medicare data.  I write about my nerdy homebrewing at <a href="http://www.brewingnerd.com">BrewingNerd.com</a>.'  
googleAnalytics: 'UA-51066876-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jason Dominiczak'
  email: jason@jasondominiczak.com
  twitter_username: brewingnerd
  github_username:  jdominiczak
  linkedin_username:  jasondominiczak
  flickr_username: jdominiczak
  instagram_username: jasondominiczak

#defaults:
#  -
#    scope:
#      path: ''
#      type: 'posts'
#    values:
#        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
